threshold: 95.1
require_exact_threshold: false
rules:
  ApiTag::Presence:
    enabled: true
    exclude: []
  ApiTag::Inclusion:
    enabled: true
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: true
    exclude: []
  ExampleTag:
    enabled: true
    exclude: []
  ReturnTag:
    enabled: true
    exclude:
      - Baleog::Adapters.with_adapter
      - Baleog::Adapters::Base#initialize
      - Baleog::Adapters::Response#initialize
      - Baleog::ClassBuilder#build
      - Baleog::ClassBuilder#build_with
      - Baleog::Client::Endpoint#initialize
      - Baleog::Client::Model#initialize
      - Baleog::Client::Model::FieldBuilder#field_name
      - Baleog::Client::Request#initialize
      - Baleog::Client::Response#initialize
      - Baleog::Client::WithEndpointOptions#initialize
      - Baleog::Endpoint#initialize
      - Baleog::NestingBuilder#complete_nesting_list
      - Baleog::NestingBuilder#inherited
  Summary::Presence:
    enabled: true
    exclude:
      - Baleog::Adapters::Base#initialize
      - Baleog::Adapters::LoaderConfig#initialize
      - Baleog::Adapters::Response#initialize
      - Baleog::ClassBuilder#build
      - Baleog::ClassBuilder#build_with
      - Baleog::ClassBuilder#initialize
      - Baleog::Client::Endpoint#initialize
      - Baleog::Client::Model#initialize
      - Baleog::Client::Request#initialize
      - Baleog::Client::Response#initialize
      - Baleog::Client::WithEndpointOptions#initialize
      - Baleog::Endpoint#initialize
      - Baleog::Model#initialize
  Summary::Length:
    enabled: true
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: true
    exclude: []
